/* Hi ?*/

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct MQTTFlags MQTTFlags;

















void construct(uint8_t *begin, uintptr_t size);

void heap_free(uint8_t *ptr);

const uint8_t *heap_test(void);

void nothing(void);

void print_pointer(const uint8_t *tag, const uint8_t *p);

/* Bye */
